"""tournaments

Revision ID: 0cc69c6eee67
Revises: None
Create Date: 2016-01-05 05:49:24.926070

"""

# revision identifiers, used by Alembic.
revision = '0cc69c6eee67'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payin', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('aborted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('rounds_count', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('defeated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('round', sa.Integer(), server_default='1', nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'tournament_id'),
    sa.UniqueConstraint('tournament_id', 'order')
    )
    op.create_index(op.f('ix_chat_message_game_id'), 'chat_message', ['game_id'], unique=False)
    op.alter_column('event', 'type',
               existing_type=mysql.ENUM('message', 'system', 'betstate', 'abort', 'report'),
               nullable=False)
    op.add_column('game', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.alter_column('game', 'gamemode',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('game', 'gamertag_creator',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('game', 'gametype',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_game_tournament_id'), 'game', ['tournament_id'], unique=False)
    op.create_foreign_key(None, 'game', 'tournament', ['tournament_id'], ['id'])
    op.create_unique_constraint(None, 'player', ['riot_summonerName'])
    op.create_unique_constraint(None, 'player', ['tibia_character'])
    op.create_unique_constraint(None, 'player', ['ea_gamertag'])
    op.create_unique_constraint(None, 'player', ['nickname'])
    op.create_unique_constraint(None, 'player', ['email'])
    op.create_unique_constraint(None, 'player', ['steam_id'])
    op.create_unique_constraint(None, 'player', ['starcraft_uid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_index(op.f('ix_game_tournament_id'), table_name='game')
    op.alter_column('game', 'gametype',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('game', 'gamertag_creator',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('game', 'gamemode',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('game', 'tournament_id')
    op.alter_column('event', 'type',
               existing_type=mysql.ENUM('message', 'system', 'betstate', 'abort', 'report'),
               nullable=True)
    op.drop_index(op.f('ix_chat_message_game_id'), table_name='chat_message')
    op.drop_table('participant')
    op.drop_table('tournament')
    ### end Alembic commands ###
