"""badges

Revision ID: 87ddc7aff543
Revises: c20f5ca325f4
Create Date: 2016-01-08 19:47:42.060598

"""

# revision identifiers, used by Alembic.
revision = '87ddc7aff543'
down_revision = 'c20f5ca325f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_badges_updated', sa.PickleType(), nullable=False),
    sa.Column('first_win', sa.PickleType(), nullable=True),
    sa.Column('first_loss', sa.PickleType(), nullable=True),
    sa.Column('played_10_games', sa.PickleType(), nullable=True),
    sa.Column('fifa15_xboxone_first_win', sa.PickleType(), nullable=True),
    sa.Column('fifa15_xboxone_first_loss', sa.PickleType(), nullable=True),
    sa.Column('fifa15_xboxone_10_wins', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badges')
    ### end Alembic commands ###
