"""tournament params

Revision ID: ada299aa8c8a
Revises: c60e3b325e86
Create Date: 2016-01-07 04:02:45.300002

"""

# revision identifiers, used by Alembic.
revision = 'ada299aa8c8a'
down_revision = 'c60e3b325e86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('gamemode', sa.String(length=64), nullable=False))
    op.add_column('tournament', sa.Column('gametype', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'gametype')
    op.drop_column('tournament', 'gamemode')
    ### end Alembic commands ###
