"""ticket creation datetime

Revision ID: c20f5ca325f4
Revises: ada299aa8c8a
Create Date: 2016-01-07 10:51:33.576689

"""

# revision identifiers, used by Alembic.
revision = 'c20f5ca325f4'
down_revision = 'ada299aa8c8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('created', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'created')
    ### end Alembic commands ###
